### ISSUE TITLE
"Hostname" [::1] breaks connection string parsing

### ISSUE THREAD

**Issue by janpio** [prisma/connection-string#10]
`sqlserver://[::1]:1433;database=prisma-demo;user=SA;password=Pr1sm4_Pr1sm4;trustServerCertificate=true;encrypt=true` should be a valid connection string in theory, but:

> Error: Error parsing connection string: Conversion error: Invalid port in `sqlserver://[::1]:1433;database=prisma-demo;user=SA;***;trustServerCertificate=true;encrypt=true`)

See: https://github.com/prisma/prisma-examples/pull/2489/checks?check_run_id=1832964769

**Comment by matthewmueller** [comment]
Just double-checked. Looks good!

**Comment by janpio** [comment]
Did this make it into a `dev` release on Prisma Client side already?

**Comment by matthewmueller** [comment]
Yah `npm install prisma@dev` picks it up.
